### PR TITLE
Create packer and terraform for QEMU

### PR DESCRIPTION
**Pull request by shanedell**
Create packer and terraform for QEMU.

- Create packer code to create VM templates for QEMU.
- Create terraform code to create VMs from VM templates for QEMU/libvirt.
- Update default version of NiFi to be 1.23.0, 1.21.0 didn't seem to work properly for VMs and has a knowm CVE.

### CODE REVIEW

**Comment by shanedell** [comment]
@rthomas320 I am not sure how much you are able to test this. If you have a Linux (Rocky/Ubuntu) machine that would be best to test this PR. This is because QEMU seemed to really only work on Linux for me. I tried it on my Mac but it didn't work out well. If you don't have a Linux, machine I would say mostly look at the code and if you have any questions or concerns leave a comment and I can help as much as possible.

**Comment by rthomas320** [comment]
I've been mostly testing on a Rocky 9 machine.  I'll try to test first thing tomorrow morning.

**Review by rthomas320 — COMMENTED** [review]
I'm getting this error when I run the provisioning on WLS Ubuntu:
TASK [noe : Set NiFi process group id] *****************************************
fatal: [default]: FAILED! => {"msg": "the field 'args' has an invalid value ({'nifi_process_group_id': '{{ (nifi_process_group_cmd.stdout | from_json).id }}'}), and could not be converted to an dict.The error was: Expecting value: line 1 column 1 (char 0)\n\nThe error appears to be in '/mnt/c/Users/rthomas/ctc-noe/noe-setup/provisioning/roles/noe/tasks/upload-template.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set NiFi process group id\n  ^ here\n"}
When I ssh in to the VM, the nifi group is present.
image
image
I didn't explicitly set a NiFi username and password, maybe the previous command to get an access token isn't working with the default username and password?

**Comment by rthomas320** [comment]
I re-tested running vagrant up to setup the Rocky VM and run the provisioning.  The provisioning failed at Enable and Start MariaDB. 
image
 However, I logged into  the VM and mariadb was running.

**Comment by rthomas320** [comment]
When I try to create the offline dependencies, I get the following error regarding python3.
image

**Comment by rthomas320** [comment]
I got a little further with the downloads for offline builds.  I had to manually install pip, in addition to ansible and docker. This is the latest error.
image

**Comment by shanedell** [comment]
That error looks like its with the request library. I saw something online that said it might be with the version of the library so if you `pip uninstall requests && pip install requests==1.84.0` and retry does it work?

**Comment by shanedell** [comment]
@rthomas320 So this is mostly issues with provisioning which really shouldn't be broken with this PR. It seems like there are random intermittent issues one of us are seeing but the other doesn't. I did also add in a check for the unzip so it only happens when that nifi folder doesn't exist. Would you be okay with me getting this merged in so I can work on the VMware packer and terraform? (that PR will definitely be merged based on how the code looks until we get a VMware instance spun up that we can test on).

**Comment by shanedell** [comment]
@rthomas320 The group seemed to approve of my last message. So I am going to merge this in and while helping trying to help resolve your issues I am going to work on the packer and terraform for VMware.

**Pull request merged**
