### PR TITLE
Auto upload NOE template. Allow setting of nifi username and password.

### PR DESCRIPTION
**Pull request by shanedell**
Auto upload NOE template. Allow setting of nifi username and password.

- Make provisioning auto upload the NOE NiFi template.
- Update provisioning to allow the user to set the nifi username and password.
  - Done through the env variable NIFI_USERNAME and NIFI_PASSWORD

### CODE REVIEW

**Comment by rthomas320** [comment]
Vagrant up hung for me during install firefox.  I'm trying to complete with vagrant provision.  I didn't get an error when the provisioning hung during the vagrant up.

**Comment by rthomas320** [comment]
The provisioning hung 2 more times, but no error was reported.  Each time I restarted the provisioning it got past the previous hang.  Maybe it was my internet connection?

**Comment by shanedell** [comment]
Yeah I am now sure I didn't have this issue. Is it happening around the new stuff or just anywhere randomly?

**Review by rthomas320 — APPROVED** [review]
I was able to build a Rocky 8 VM with the provisioning.  The NiFi GUI started with the saved passwords. The NOE NiFi template was already uploaded in NiFi when I brought it up.  The test files processed through NiFi. NiFi successfully updated the processing data to the database tables.

**Pull request merged**
